import { describe, it, expect } from 'vitest';
import { parseSummariseResponse, truncateExplanation } from './aiParser';

describe('aiParser', () => {
  const requestedIds = ['node_1', 'node_2'];

  it('parses valid JSON response', () => {
    const raw = JSON.stringify({
      node_1: 'elementwise tensor addition',
      node_2: 'input tensor argument',
    });
    const parsed = parseSummariseResponse(raw, requestedIds);
    expect(parsed).toEqual({
      node_1: 'elementwise tensor addition',
      node_2: 'input tensor argument',
    });
  });

  it('parses Markdown code fenced JSON response', () => {
    const raw = "```json\n{\n  \"node_1\": \"adds two floats\",\n  \"node_2\": \"input parameter\"\n}\n```";
    const parsed = parseSummariseResponse(raw, requestedIds);
    expect(parsed).toEqual({
      node_1: 'adds two floats',
      node_2: 'input parameter',
    });
  });

  it('parses wrapped object response such as { summaries: { ... } }', () => {
    const raw = JSON.stringify({
      summaries: {
        node_1: 'elementwise addition',
        node_2: 'input tensor',
      },
    });
    const parsed = parseSummariseResponse(raw, requestedIds);
    expect(parsed).toEqual({
      node_1: 'elementwise addition',
      node_2: 'input tensor',
    });
  });

  it('handles 10+ visible nodes producing summary mappings for all valid IDs', () => {
    const manyIds = Array.from({ length: 12 }, (_, i) => `node_${i + 1}`);
    const summariesMap: Record<string, string> = {};
    manyIds.forEach((id, i) => {
      summariesMap[id] = `Summary for node ${i + 1}`;
    });

    const raw = JSON.stringify({ summaries: summariesMap });
    const parsed = parseSummariseResponse(raw, manyIds);
    expect(Object.keys(parsed)).toHaveLength(12);
    manyIds.forEach((id) => {
      expect(parsed[id]).toBeDefined();
    });
  });

  it('preserves valid node summaries even if one summary is malformed or empty', () => {
    const ids = ['node_1', 'node_2', 'node_3'];
    const raw = JSON.stringify({
      node_1: 'matrix multiplication',
      node_2: '', // empty summary
      node_3: null, // invalid type
    });

    const parsed = parseSummariseResponse(raw, ids);
    expect(parsed).toEqual({
      node_1: 'matrix multiplication',
    });
  });

  it('truncates summaries to a maximum of 5 words', () => {
    const raw = JSON.stringify({
      node_1: 'this is a very long summary string that exceeds five words',
    });
    const parsed = parseSummariseResponse(raw, requestedIds);
    expect(parsed).toEqual({
      node_1: 'this is a very long',
    });
  });

  it('ignores unknown node IDs and retains requested IDs', () => {
    const raw = JSON.stringify({
      node_1: 'tensor operation',
      unknown_node: 'should be ignored',
    });
    const parsed = parseSummariseResponse(raw, requestedIds);
    expect(parsed).toEqual({
      node_1: 'tensor operation',
    });
  });

  it('throws error for malformed JSON', () => {
    expect(() => parseSummariseResponse('not json', requestedIds)).toThrow(
      'AI response could not be parsed as JSON.'
    );
  });

  it('throws error for non-object JSON', () => {
    expect(() => parseSummariseResponse('["item1", "item2"]', requestedIds)).toThrow(
      'AI response was not a valid JSON object'
    );
  });

  it('throws error when no matching node summaries are returned', () => {
    const raw = JSON.stringify({ unrelated_id: 'some text' });
    expect(() => parseSummariseResponse(raw, requestedIds)).toThrow(
      'AI summary response contained no valid node ID summary mappings.'
    );
  });

  it('truncates explanations exceeding maxWords at a sentence boundary', () => {
    const sentence1 = 'This operation performs elementwise addition of two input tensors.';
    const sentence2 = 'It is generated by the compiler to fold binary arithmetic ops into a single kernel execution.';
    const sentence3 = 'This allows lower memory bandwidth overhead across GPU execution boundaries.';
    const sentence4 = 'Extra sentence that forces word count way beyond one hundred words to test safety bounds cutoff.';

    const longText = `${sentence1} ${sentence2} ${sentence3} ${sentence4}`;
    const truncated = truncateExplanation(longText, 30);
    expect(truncated.split(/\s+/).length).toBeLessThanOrEqual(30);
    expect(truncated.endsWith('.')).toBe(true);
  });
});
